// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace DeathLearnV2ML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public string Button { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public float PlayerX { get; set; }


        [ColumnName("col2"), LoadColumn(2)]
        public float PlayerY { get; set; }


        [ColumnName("col3"), LoadColumn(3)]
        public float EnemyX { get; set; }


        [ColumnName("col4"), LoadColumn(4)]
        public float EnemyY { get; set; }


        [ColumnName("col5"), LoadColumn(5)]
        public float EnemyVelocityX { get; set; }


        [ColumnName("col6"), LoadColumn(6)]
        public float EnemyVelocityY { get; set; }

        [ColumnName("col7"), LoadColumn(7)]
        public float ClosestArrowX { get; set; }

        [ColumnName("col8"), LoadColumn(8)]
        public float ClosestArrowY { get; set; }


    }
}
