// This file was auto-generated by ML.NET Model Builder. 

using System;
using DeathLearnV2ML.Model;

namespace DeathLearnV2ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            do
            {
                string input = Console.ReadLine();
                string[] inputArgs = input.Split(' ');

                ModelInput modelInput = new ModelInput()
                {
                    PlayerX = float.Parse(inputArgs[0]),
                    PlayerY = float.Parse(inputArgs[1]),
                    EnemyX = float.Parse(inputArgs[2]),
                    EnemyY = float.Parse(inputArgs[3]),
                    EnemyVelocityX = float.Parse(inputArgs[4]),
                    EnemyVelocityY = float.Parse(inputArgs[5]),
                };

                var predictionResult = ConsumeModel.Predict(modelInput);

                Console.WriteLine(predictionResult.Prediction);

            } while (true);


            // Create single instance of sample data from first line of dataset for model input
            //ModelInput sampleData = new ModelInput()
            //{
            //    PlayerX = float.Parse(args[0]),
            //    PlayerY = float.Parse(args[1]),
            //    EnemyX = float.Parse(args[2]),
            //    EnemyY = float.Parse(args[3]),
            //    EnemyVelocityX = float.Parse(args[4]),
            //    EnemyVelocityY = float.Parse(args[5]),
            //};

            //// Make a single prediction on the sample data and print results
            //var predictionResult = ConsumeModel.Predict(sampleData);

            //Console.WriteLine(predictionResult.Prediction);

            //Console.WriteLine("Using model to make single prediction -- Comparing actual Col0 with predicted Col0 from sample data...\n\n");
            //Console.WriteLine($"Col1: {sampleData.PlayerX}");
            //Console.WriteLine($"Col2: {sampleData.PlayerY}");
            //Console.WriteLine($"Col3: {sampleData.EnemyX}");
            //Console.WriteLine($"Col4: {sampleData.EnemyY}");
            //Console.WriteLine($"Col5: {sampleData.EnemyVelocityX}");
            //Console.WriteLine($"Col6: {sampleData.EnemyVelocityY}");
            //Console.WriteLine($"\n\nPredicted Col0 value {predictionResult.Prediction} \nPredicted Col0 scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            //Console.WriteLine("=============== End of process, hit any key to finish ===============");
            //Console.ReadKey();
        }
    }
}
